analyzer:
  # Enable only necessary lints for the plugin
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Exclude generated files and build artifacts
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/node_modules/**"
    - "**/x.c.dart"

  # Performance optimizations
  errors:
    # Disable some expensive checks for plugin development
    invalid_annotation_target: ignore
    invalid_use_of_protected_member: ignore

linter:
  rules:
    # Performance-focused rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_unnecessary_containers: true
