name: host_plugin
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^6.6.0
  analyzer_plugin: ^0.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
