name: host_plugin
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ">=7.5.9 <8.0.0"
  analyzer_plugin: ">=0.13.0 <1.0.0"
