name: analyzer_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.11.3
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analyzer_plugin

environment:
  sdk: '^3.0.0'

dependencies:
  analyzer: ^6.0.0
  collection: ^1.17.0
  dart_style: ^2.2.1
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  analyzer_utilities:
    path: ../analyzer_utilities
  # lints: ^2.0.0
  # linter: ^1.10.0
  meta: ^1.10.0
  path: ^1.8.0
  # test_reflective_loader: ^3.0.0
  test: ^1.24.0