name: analyzer
version: 6.5.0
description: >-
  This package provides a library that performs static analysis of Dart code.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analyzer

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  _fe_analyzer_shared: ^72.0.0
  collection: ^1.19.0
  convert: ^3.0.0
  crypto: ^3.0.0
  glob: ^2.0.0
  macros: '>=0.1.2-main.3 <0.1.3'
  meta: ^1.15.0
  package_config: ^2.0.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  source_span: ^1.8.0
  watcher: ^1.1.0
  yaml: ^3.0.0

# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
dev_dependencies:
  analyzer_utilities:
    path: ../analyzer_utilities
  args: any
  async: any
  checks: any
  heap_snapshot:
    path: ../heap_snapshot
  linter:
    path: ../linter
  # lints: any
  matcher: any
  vm_service:
    path: ../vm_service

dependency_overrides:
  _fe_analyzer_shared:
    path: ../_fe_analyzer_shared
  analyzer_utilities:
    path: ../analyzer_utilities
  heap_snapshot:
    path: ../heap_snapshot
  linter:
    path: ../linter
  vm_service:
    path: ../vm_service
